### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by StefanKoenen** [appknox/droid-VNC-server#11]
Are there links to a working APK for the different versions?

**Comment by nfsprodriver** [comment]
Here is a new apk with some contributions. Have fun ;)
https://github.com/nfsprodriver/droid-VNC-server/releases

**Comment by StefanKoenen** [comment]
@nfsprodriver Thanks alot!
However I have an issue when I try to compile the source myself, do I miss something / some setup?
![image](https://user-images.githubusercontent.com/1442819/55899556-61dbf200-5bc5-11e9-9f59-a655021cdc85.png)

Full output: https://pastebin.com/dgD0qDd1

**Comment by nfsprodriver** [comment]
Maybe I missed something. Will have a look to your log later. Used NDK 15.

Am 10. April 2019 19:18:57 schrieb Stefan <notifications@github.com>:
" @nfsprodriver Thanks alot!
" However I have an issue when I try to compile the source myself, do I 
miss something / some setup?
"
" Full output: https://pastebin.com/dgD0qDd1
" —
" You are receiving this because you were mentioned.
" Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by nfsprodriver** [comment]
Yepp, also had these .func / .endfunc macros. Worked with NDK 15.

Am 10. April 2019 19:18:57 schrieb Stefan <notifications@github.com>:
" @nfsprodriver Thanks alot!
" However I have an issue when I try to compile the source myself, do I 
miss something / some setup?
"
" Full output: https://pastebin.com/dgD0qDd1
" —
" You are receiving this because you were mentioned.
" Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by StefanKoenen** [comment]
hmm ok, I was using latest android studio / NDK 19.xxx

**Comment by Shubham-Quadrish** [comment]
had this issue ,
What should i do now, thanks

        .func png_read_filter_row_sub4_neon
        ^
jni/libpng/arm/filter_neon.S:40:1: note: while in macro instantiation
func png_read_filter_row_sub4_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:54:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_sub3_neon
        ^
jni/libpng/arm/filter_neon.S:56:1: note: while in macro instantiation
func png_read_filter_row_sub3_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:80:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_up_neon
        ^
jni/libpng/arm/filter_neon.S:82:1: note: while in macro instantiation
func png_read_filter_row_up_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:93:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_avg4_neon
        ^
jni/libpng/arm/filter_neon.S:95:1: note: while in macro instantiation
func png_read_filter_row_avg4_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:114:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_avg3_neon
        ^
jni/libpng/arm/filter_neon.S:116:1: note: while in macro instantiation
func png_read_filter_row_avg3_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:149:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_paeth4_neon
        ^
jni/libpng/arm/filter_neon.S:167:1: note: while in macro instantiation
func png_read_filter_row_paeth4_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:188:1: note: while in macro instantiation
endfunc
^
<instantiation>:11:9: error: unknown directive
        .func png_read_filter_row_paeth3_neon
        ^
jni/libpng/arm/filter_neon.S:190:1: note: while in macro instantiation
func png_read_filter_row_paeth3_neon, export=1
^
<instantiation>:2:9: error: unknown directive
        .endfunc
        ^
jni/libpng/arm/filter_neon.S:225:1: note: while in macro instantiation
endfunc
^
make: *** [obj/local/armeabi-v7a/objs-debug/png/arm/filter_neon.o] Error 1
